### ISSUE TITLE
Wrong type argument: listp, nano-modeline--empty-face

### ISSUE THREAD

**Issue by teesh3rt** [rougier/nano-modeline#59]
I try to execute `(nano-modeline-text-mode t)`, but it just shows this!:
`Wrong type argument: listp, nano-modeline--empty-face`
can anybody help me fix this?

**Comment by yakhni** [comment]
Facing the same issue...

**Comment by rougier** [comment]
I just pushed a fix on ELPA that hopefully will solve the problem. Just wait a few minutes for ELPA to update and update the package.

**Comment by rougier** [comment]
How is it not working?

**Comment by coldfish** [comment]
Still getting the same error: `(wrong-type-argument listp nano-modeline--empty-face)`

Before upgrading the library, I was using this:

```
(use-package! nano-modeline
  :config
  (nano-modeline-mode))
```

**Comment by rougier** [comment]
Could you try opening the nano-modeline.el file (from github) and evaluate the buffer?

**Comment by beneklins** [comment]
Using vanilla Emacs 28.2, `emacs -Q`, and evaluating `nano-modeline.el` @ [a18780c](https://github.com/rougier/nano-modeline/commit/a18780c277838983932623870752f0adddef0345), I get the error reported above. For completeness, the stack trace is
```elisp
Debugger entered--Lisp error: (wrong-type-argument listp nano-modeline--empty-face)
  face-remap-set-base(header-line nano-modeline--empty-face)
  nano-modeline-header(((nano-modeline-buffer-status) " " (nano-modeline-buffer-name) " " (nano-modeline-git-info)) ((nano-modeline-cursor-position) (nano-modeline-window-dedicated)) nil)
  funcall(nano-modeline-header ((nano-modeline-buffer-status) " " (nano-modeline-buffer-name) " " (nano-modeline-git-info)) ((nano-modeline-cursor-position) (nano-modeline-window-dedicated)) nil)
  nano-modeline-prog-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook))
  run-mode-hooks(prog-mode-hook)
  prog-mode()
  funcall-interactively(prog-mode)
  call-interactively(prog-mode record nil)
  command-execute(prog-mode record)
  execute-extended-command(nil "prog-mode" nil)
  funcall-interactively(execute-extended-command nil "prog-mode" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by aaronjensen** [comment]
https://github.com/emacs-mirror/emacs/commit/7b0b27971b583c09cbc524d2215546f5dfe4a0e1

This is fixed in later (unreleased) versions of Emacs. 

I don't know if there is or what the workaround would be

**Comment by rougier** [comment]
Sorry for late answer. @aaronjensen You mean the problem comes from Emacs itself?

**Comment by aaronjensen** [comment]
Correct. They broke it somewhat recently and have fixed it, but last I checked the fix was not released.

**Comment by rougier** [comment]
Better is to wait I guess. Or anyone sees a workaround?

**Comment by aaronjensen** [comment]
The only work around I can think of would be to do pass an extra nil:

```el
(face-remap-set-base 'header-line 'nano-modeline--empty-face nil)
```

This probably doesn't have much impact (I believe the nil is treated as an empty property list), it's just a hack.

**Comment by rougier** [comment]
Back to work. What would be the limitations of the code above exactly?

**Comment by aaronjensen** [comment]
Now that Emacs 29.1 is released this may be moot unless you want to support Emacs 28.
